### PR TITLE
load environment when running sync_static task

### PR DESCRIPTION
**Pull request by krishantaylor**
This got lost in the addition of syncing non-image assets. Adding back so rails environment is loaded as a dependency.

### CODE REVIEW

**Comment by gtmax** [comment]
@krishantaylor Does something depend on rails in this flow?

**Comment by krishantaylor** [comment]
I pretty sure the `environment` rake task is coming from rails. This is basically a redo of #177. For some reason, the `environment` dependency was lost in #241 (https://github.com/cloudinary/cloudinary_gem/pull/241/files#diff-bf612e3e6edbec014c707888236e9901L3).

**Comment by dzeitman** [comment]
Yes, the environment rake task loads rails, but in this instance we're not dependent on rails.  loading will make the task run slower, since there's no dependency needed for this task.

**Comment by krishantaylor** [comment]
The task doesn't run correctly in a rails environment without this when the gem is configured with an initializer (as outlined in [the docs](https://cloudinary.com/documentation/rails_additional_topics#configuration_options). What do you suggest as a better fix?

**Comment by gtmax** [comment]
Ah, now I see what you mean, great point! Agreed, with that in mind this fix completely makes sense. Thanks @krishantaylor!

**Comment by tocker** [comment]
@krishantaylor thanks for the pull request!

**Pull request merged**
