### PR TITLE
support for mount_uploaders

### PR DESCRIPTION
**Pull request by ollym**
### Brief Summary of Changes
Support for `mount_uploaders`

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [ ] New feature
- [X] Bug fix
- [ ] Adds more tests

#### Are tests included?
- [ ] Yes
- [X] No

#### Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I ran the full test suite before pushing the changes and all the tests pass.

### CODE REVIEW

**Comment by ollym** [comment]
@const-cloudinary any news?

**Comment by wissam-khalili** [comment]
Hi @ollym ,

Thank you for your contribution.
I would like to update you that it will be released in the next version.

Best Regards,
Wissam

**Comment by ollym** [comment]
@wissam-khalili any ideas when that will be cut?

**Comment by wissam-khalili** [comment]
@const-cloudinary Could you share when it will be cut?

**Comment by wissam-khalili** [comment]
Hi @ollym ,

I want to update you that the fix was released in the latest version.

Best Regards,
Wissam

**Pull request merged**
