### PR TITLE
Add accepted_formats to `accept` file upload attribute

### PR DESCRIPTION
**Pull request by MikeRogers0**
This will take the allowed_formats option and convert it into a value
suitable for the `accept` file input attribute, for example:

```
<%= f.cl_image_upload(:avatar, allowed_formats: %w(jpg jpeg gif png)) %>
```

Would output:

```
 <input type="file" name="file"
 accept=".jpg,.jpeg,.gif,.png"
 class="cloudinary-fileupload" />
```

### CODE REVIEW

**Comment by MikeRogers0** [comment]
CI looks to be failing because `cloud_name = options[:cloud_name] || Cloudinary.config.cloud_name || raise("Must supply cloud_name")` - Though, it's also failing in master for me :/

Any idea how to fix?

**Comment by MikeRogers0** [comment]
@tocker - Any thoughts on this?

**Comment by tocker** [comment]
Hi @MikeRogers0,

Thanks for the pull request!
You can pass html attributes to `cl_upload` with the `html:` key:

```
<%= f.cl_image_upload(:image, html: {accept: ".jpg,.jpeg,.gif,.png"}) %>
```

Adding `allowed_formats` seems redundant unless you another reason for having it?

**Regarding the CI failure**: TravisCI will not pass encrypted variables to external PRs ([source](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions)). Our tests require api_key and api_secret and fail without them.

We are planning to implement a solution for this issue.

**Comment by MikeRogers0** [comment]
@tocker The `allowed_fomats` argument currently gets passed to the uploader params ( https://github.com/cloudinary/cloudinary_gem/blob/5674d61f7a7750a753f9e26e5f8f20efd9e7c155/lib/cloudinary/uploader.rb#L22 ) (So a file can be rejected by Cloudinary if it's not right), so this aims to reduce the need for doing:

`<%= f.cl_image_upload(:image, allowed_fomats: %w(jpg jpeg gif png), html: {accept: ".jpg,.jpeg,.gif,.png"}) %>`

**Comment by tocker** [comment]
@MikeRogers0 When provided `allow_formats` Cloudinary checks the actual content of the file. This means that currently you can use a different `accept` values to the `allow_formats`, allowing users to choose image files that don't have an extension or have a mismatching extension but still filter the actual file content.

Your proposed change will restrict the input to file with extensions defined in `allow_formats` which defeats the purpose of the argument.

**Comment by MikeRogers0** [comment]
Oh I understand :) I’ll close this, thank you regardless :)

**Pull request closed without merging**
